# Fail2Ban filter for asterisk authentication failures
#

[INCLUDES]
before = common.conf

[Definition]
_daemon = asterisk
__pid_re = (?:\s*\[\d+\])
iso8601 = \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d+[+-]\d{4}

log_prefix= (?:NOTICE|SECURITY|WARNING)%(__pid_re)s:?(?:\[C-[\da-f]*\])? \S+:\d*( in \w+:)?

failregex = ^(.*)AOR '' not found for endpoint 'anonymous' \(<HOST>:\d+\)(.*)$
        ^(.*)anonymous: Call \(UDP:<HOST>.*\) to extension '.*' rejected because extension not found in context (.*)$
        ^(.*)anonymous: Call \(UDP:<HOST>:\d+\) to extension '.*' rejected because extension not found in context 'anonymous'(.*)$

ignoreregex =
datepattern = {^LN-BEG}
journalmatch = _SYSTEMD_UNIT=asterisk.service

[lt_journal]

__extra_timestamp = (?:\[[^\]]+\]\s+)?
__prefix_line = %(known/__prefix_line)s%(__extra_timestamp)s
